//===========================================================================
// 
// Modern Warfare 0.1
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Barade
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    force                   udg_ForceGovernment        = null
    force                   udg_ForceRebels            = null
    force                   udg_ForceCivilians         = null

    // Generated
    trigger                 gg_trg_Initialization      = null
    trigger                 gg_trg_Init_Forces         = null
    trigger                 gg_trg_Start_Remove_Units_of_Players = null
    trigger                 gg_trg_Start_AI            = null
    trigger                 gg_trg_Start_Alliances     = null
    trigger                 gg_trg_Start_Workers_Collecting_Gold = null
endglobals

function InitGlobals takes nothing returns nothing
    set udg_ForceGovernment = CreateForce()
    set udg_ForceRebels = CreateForce()
    set udg_ForceCivilians = CreateForce()
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', -5952.0, -3328.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'H009', -5942.4, -3775.8, 270.000, 'H009' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5994.2, -3045.4, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5925.4, -3052.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5843.3, -3047.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5785.8, -3050.5, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -6056.3, -3051.6, 270.000, 'h001' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', -5184.0, -3328.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', -5294.8, -3041.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5024.3, -3040.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5081.8, -3036.6, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5163.9, -3041.7, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5232.7, -3034.9, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', -5177.4, -3785.5, 270.000, 'H009' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer2 takes nothing returns nothing
    local player p = Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', -5952.0, -4608.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer2 takes nothing returns nothing
    local player p = Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', -6038.7, -4894.8, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5969.9, -4901.7, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5887.9, -4896.6, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5830.3, -4900.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -6100.8, -4901.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', -5968.0, -4307.2, 90.000, 'H009' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', -5120.0, -4608.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'H009', -5112.1, -4281.7, 90.000, 'H009' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5264.0, -4907.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -4993.5, -4906.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5051.1, -4902.7, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5133.1, -4907.8, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', -5201.9, -4900.9, 270.000, 'h001' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer4 takes nothing returns nothing
    local player p = Player(4)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', 2816.0, 2496.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer4 takes nothing returns nothing
    local player p = Player(4)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', 2711.4, 2190.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2780.1, 2183.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2862.2, 2188.3, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2919.8, 2184.8, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2649.2, 2183.7, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', 2946.9, 2997.6, 270.000, 'H009' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer5 takes nothing returns nothing
    local player p = Player(5)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', 3328.0, 2496.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer5 takes nothing returns nothing
    local player p = Player(5)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', 3254.2, 2201.3, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3322.9, 2194.5, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3405.0, 2199.6, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3471.1, 2193.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3192.0, 2195.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', 3455.9, 2987.9, 270.000, 'H009' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer6 takes nothing returns nothing
    local player p = Player(6)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', 2816.0, 3840.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer6 takes nothing returns nothing
    local player p = Player(6)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', 2789.3, 4280.4, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2858.1, 4273.6, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2940.2, 4278.7, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2997.8, 4275.3, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 2727.2, 4274.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', 2883.4, 3501.8, 270.000, 'H009' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer7 takes nothing returns nothing
    local player p = Player(7)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h000', 3328.0, 3840.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateUnitsForPlayer7 takes nothing returns nothing
    local player p = Player(7)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', 3244.0, 4268.1, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3514.5, 4269.2, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3457.0, 4272.6, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3374.9, 4267.5, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h001', 3306.1, 4274.3, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'H009', 3366.5, 3473.9, 270.000, 'H009' )
endfunction

//===========================================================================
function CreateUnitsForPlayer8 takes nothing returns nothing
    local player p = Player(8)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n000', -3113.4, -61.5, 270.000, 'n000' )
    set u = BlzCreateUnitWithSkin( p, 'n001', -3004.9, -69.1, 270.000, 'n001' )
    set u = BlzCreateUnitWithSkin( p, 'n002', -3125.1, -181.2, 270.000, 'n002' )
    set u = BlzCreateUnitWithSkin( p, 'n003', -3005.5, -180.2, 270.000, 'n003' )
    set u = BlzCreateUnitWithSkin( p, 'h00I', -3009.5, 813.3, 90.000, 'h00I' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -3127.1, 67.3, 270.000, 'n006' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -3002.1, 61.2, 270.000, 'n006' )
endfunction

//===========================================================================
function CreateUnitsForPlayer9 takes nothing returns nothing
    local player p = Player(9)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n000', -2863.3, -71.4, 270.000, 'n000' )
    set u = BlzCreateUnitWithSkin( p, 'n001', -2754.8, -79.0, 270.000, 'n001' )
    set u = BlzCreateUnitWithSkin( p, 'n002', -2874.9, -191.0, 270.000, 'n002' )
    set u = BlzCreateUnitWithSkin( p, 'n003', -2755.3, -190.0, 270.000, 'n003' )
    set u = BlzCreateUnitWithSkin( p, 'h00I', -3257.0, 814.5, 90.000, 'h00I' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2878.1, 66.6, 270.000, 'n006' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2737.5, 68.5, 270.000, 'n006' )
endfunction

//===========================================================================
function CreateUnitsForPlayer10 takes nothing returns nothing
    local player p = Player(10)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n000', -2612.4, -75.3, 270.000, 'n000' )
    set u = BlzCreateUnitWithSkin( p, 'n001', -2504.0, -82.9, 270.000, 'n001' )
    set u = BlzCreateUnitWithSkin( p, 'n002', -2624.1, -195.0, 270.000, 'n002' )
    set u = BlzCreateUnitWithSkin( p, 'n003', -2504.5, -194.0, 270.000, 'n003' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2595.4, 57.0, 270.000, 'n006' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2485.2, 61.5, 270.000, 'n006' )
endfunction

//===========================================================================
function CreateUnitsForPlayer11 takes nothing returns nothing
    local player p = Player(11)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n000', -2362.1, -78.2, 270.000, 'n000' )
    set u = BlzCreateUnitWithSkin( p, 'n001', -2253.7, -85.8, 270.000, 'n001' )
    set u = BlzCreateUnitWithSkin( p, 'n002', -2373.8, -197.9, 270.000, 'n002' )
    set u = BlzCreateUnitWithSkin( p, 'n003', -2254.2, -196.9, 270.000, 'n003' )
    set u = BlzCreateUnitWithSkin( p, 'h00J', -3140.6, 804.4, 90.000, 'h00J' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2364.0, 65.9, 270.000, 'n006' )
    set u = BlzCreateUnitWithSkin( p, 'n006', -2252.7, 64.2, 270.000, 'n006' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer12 takes nothing returns nothing
    local player p = Player(12)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n004', -2592.0, 928.0, 270.000, 'n004' )
    set u = BlzCreateUnitWithSkin( p, 'n005', -800.0, -160.0, 270.000, 'n005' )
    set u = BlzCreateUnitWithSkin( p, 'n007', 160.0, 2336.0, 270.000, 'n007' )
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n00B', -1312.0, -1696.0, 270.000, 'n00B' )
    set u = BlzCreateUnitWithSkin( p, 'ngol', -5952.0, -2752.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', -5184.0, -2752.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', -6016.0, -5376.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', -5184.0, -5376.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ntav', -6336.0, -3968.0, 270.000, 'ntav' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'n008', -2016.0, -1568.0, 270.000, 'n008' )
    set u = BlzCreateUnitWithSkin( p, 'n009', -2976.0, -1376.0, 270.000, 'n009' )
    set u = BlzCreateUnitWithSkin( p, 'n00A', -288.0, 1056.0, 270.000, 'n00A' )
    set u = BlzCreateUnitWithSkin( p, 'ngol', 2880.0, 1728.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', 3392.0, 1728.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', 2880.0, 4736.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ngol', 3392.0, 4736.0, 270.000, 'ngol' )
    call SetResourceAmount( u, 1000000 )
    set u = BlzCreateUnitWithSkin( p, 'ntav', 4096.0, 3136.0, 270.000, 'ntav' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
    call CreateBuildingsForPlayer1(  )
    call CreateBuildingsForPlayer2(  )
    call CreateBuildingsForPlayer3(  )
    call CreateBuildingsForPlayer4(  )
    call CreateBuildingsForPlayer5(  )
    call CreateBuildingsForPlayer6(  )
    call CreateBuildingsForPlayer7(  )
    call CreateBuildingsForPlayer12(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
    call CreateUnitsForPlayer1(  )
    call CreateUnitsForPlayer2(  )
    call CreateUnitsForPlayer3(  )
    call CreateUnitsForPlayer4(  )
    call CreateUnitsForPlayer5(  )
    call CreateUnitsForPlayer6(  )
    call CreateUnitsForPlayer7(  )
    call CreateUnitsForPlayer8(  )
    call CreateUnitsForPlayer9(  )
    call CreateUnitsForPlayer10(  )
    call CreateUnitsForPlayer11(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings(  )
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Initialization_Func005A takes nothing returns nothing
    call SetPlayerMaxHeroesAllowed( 1, GetEnumPlayer() )
endfunction

function Trig_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility(  )
    call MeleeStartingHeroLimit(  )
    call MeleeStartingResources(  )
    call ForForce( GetPlayersAll(), function Trig_Initialization_Func005A )
endfunction

//===========================================================================
function InitTrig_Initialization takes nothing returns nothing
    set gg_trg_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Initialization, function Trig_Initialization_Actions )
endfunction

//===========================================================================
// Trigger: Init Forces
//===========================================================================
function Trig_Init_Forces_Actions takes nothing returns nothing
    call ForceAddPlayerSimple( Player(0), udg_ForceGovernment )
    call ForceAddPlayerSimple( Player(1), udg_ForceGovernment )
    call ForceAddPlayerSimple( Player(2), udg_ForceGovernment )
    call ForceAddPlayerSimple( Player(3), udg_ForceGovernment )
    call ForceAddPlayerSimple( Player(4), udg_ForceRebels )
    call ForceAddPlayerSimple( Player(5), udg_ForceRebels )
    call ForceAddPlayerSimple( Player(6), udg_ForceRebels )
    call ForceAddPlayerSimple( Player(7), udg_ForceRebels )
    call ForceAddPlayerSimple( Player(8), udg_ForceCivilians )
    call ForceAddPlayerSimple( Player(9), udg_ForceCivilians )
    call ForceAddPlayerSimple( Player(10), udg_ForceCivilians )
    call ForceAddPlayerSimple( Player(11), udg_ForceCivilians )
    call ForceAddPlayerSimple( Player(12), udg_ForceCivilians )
endfunction

//===========================================================================
function InitTrig_Init_Forces takes nothing returns nothing
    set gg_trg_Init_Forces = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Init_Forces, function Trig_Init_Forces_Actions )
endfunction

//===========================================================================
// Trigger: Start Remove Units of Players
//===========================================================================
function Trig_Start_Remove_Units_of_Players_Func002Func002A takes nothing returns nothing
    call RemoveUnit( GetEnumUnit() )
endfunction

function Trig_Start_Remove_Units_of_Players_Func002A takes nothing returns nothing
    set bj_wantDestroyGroup = true
    call ForGroupBJ( GetUnitsOfPlayerAll(GetEnumPlayer()), function Trig_Start_Remove_Units_of_Players_Func002Func002A )
endfunction

function Trig_Start_Remove_Units_of_Players_Actions takes nothing returns nothing
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_NONE), function Trig_Start_Remove_Units_of_Players_Func002A )
endfunction

//===========================================================================
function InitTrig_Start_Remove_Units_of_Players takes nothing returns nothing
    set gg_trg_Start_Remove_Units_of_Players = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Start_Remove_Units_of_Players, 0.00 )
    call TriggerAddAction( gg_trg_Start_Remove_Units_of_Players, function Trig_Start_Remove_Units_of_Players_Actions )
endfunction

//===========================================================================
// Trigger: Start AI
//===========================================================================
function Trig_Start_AI_Func001Func001Func002A takes nothing returns nothing
    call RemoveUnit( GetEnumUnit() )
endfunction

function Trig_Start_AI_Func001Func001C takes nothing returns boolean
    if ( not ( GetPlayerSlotState(GetEnumPlayer()) == PLAYER_SLOT_STATE_PLAYING ) ) then
        return false
    endif
    return true
endfunction

function Trig_Start_AI_Func001A takes nothing returns nothing
    if ( Trig_Start_AI_Func001Func001C() ) then
        call StartCampaignAI( GetEnumPlayer(), "war3mapImported\\modernwarfare.ai" )
    else
        set bj_wantDestroyGroup = true
        call ForGroupBJ( GetUnitsOfPlayerAll(GetEnumPlayer()), function Trig_Start_AI_Func001Func001Func002A )
        call CustomDefeatBJ( GetEnumPlayer(), "TRIGSTR_109" )
    endif
endfunction

function Trig_Start_AI_Actions takes nothing returns nothing
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_COMPUTER), function Trig_Start_AI_Func001A )
endfunction

//===========================================================================
function InitTrig_Start_AI takes nothing returns nothing
    set gg_trg_Start_AI = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Start_AI, 0.00 )
    call TriggerAddAction( gg_trg_Start_AI, function Trig_Start_AI_Actions )
endfunction

//===========================================================================
// Trigger: Start Alliances
//===========================================================================
function Trig_Start_Alliances_Func007Func001C takes nothing returns boolean
    if ( not ( GetEnumPlayer() != Player(12) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Start_Alliances_Func007A takes nothing returns nothing
    if ( Trig_Start_Alliances_Func007Func001C() ) then
        call SetForceAllianceStateBJ( GetForceOfPlayer(GetEnumPlayer()), GetPlayersAllies(GetEnumPlayer()), bj_ALLIANCE_ALLIED_ADVUNITS )
    else
        call DoNothing(  )
    endif
endfunction

function Trig_Start_Alliances_Actions takes nothing returns nothing
    call SetForceAllianceStateBJ( udg_ForceCivilians, udg_ForceGovernment, bj_ALLIANCE_NEUTRAL )
    call SetForceAllianceStateBJ( udg_ForceCivilians, udg_ForceRebels, bj_ALLIANCE_NEUTRAL )
    call SetForceAllianceStateBJ( udg_ForceGovernment, udg_ForceCivilians, bj_ALLIANCE_NEUTRAL )
    call SetForceAllianceStateBJ( udg_ForceRebels, udg_ForceCivilians, bj_ALLIANCE_NEUTRAL )
    call SetForceAllianceStateBJ( GetForceOfPlayer(Player(12)), udg_ForceCivilians, bj_ALLIANCE_ALLIED_ADVUNITS )
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_COMPUTER), function Trig_Start_Alliances_Func007A )
endfunction

//===========================================================================
function InitTrig_Start_Alliances takes nothing returns nothing
    set gg_trg_Start_Alliances = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Start_Alliances, 0.00 )
    call TriggerAddAction( gg_trg_Start_Alliances, function Trig_Start_Alliances_Actions )
endfunction

//===========================================================================
// Trigger: Start Workers Collecting Gold
//===========================================================================
function Trig_Start_Workers_Collecting_Gold_Func002A takes nothing returns nothing
endfunction

function Trig_Start_Workers_Collecting_Gold_Actions takes nothing returns nothing
    set bj_wantDestroyGroup = true
    call ForGroupBJ( GetUnitsOfPlayerAndTypeId(Player(0), 'h001'), function Trig_Start_Workers_Collecting_Gold_Func002A )
endfunction

//===========================================================================
function InitTrig_Start_Workers_Collecting_Gold takes nothing returns nothing
    set gg_trg_Start_Workers_Collecting_Gold = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Start_Workers_Collecting_Gold, 0.00 )
    call TriggerAddAction( gg_trg_Start_Workers_Collecting_Gold, function Trig_Start_Workers_Collecting_Gold_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Initialization(  )
    call InitTrig_Init_Forces(  )
    call InitTrig_Start_Remove_Units_of_Players(  )
    call InitTrig_Start_AI(  )
    call InitTrig_Start_Alliances(  )
    call InitTrig_Start_Workers_Collecting_Gold(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Initialization )
    call ConditionalTriggerExecute( gg_trg_Init_Forces )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(1), false )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call ForcePlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(2), false )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )

    // Player 4
    call SetPlayerStartLocation( Player(4), 4 )
    call ForcePlayerStartLocation( Player(4), 4 )
    call SetPlayerColor( Player(4), ConvertPlayerColor(4) )
    call SetPlayerRacePreference( Player(4), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(4), false )
    call SetPlayerController( Player(4), MAP_CONTROL_COMPUTER )

    // Player 5
    call SetPlayerStartLocation( Player(5), 5 )
    call ForcePlayerStartLocation( Player(5), 5 )
    call SetPlayerColor( Player(5), ConvertPlayerColor(5) )
    call SetPlayerRacePreference( Player(5), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(5), false )
    call SetPlayerController( Player(5), MAP_CONTROL_USER )

    // Player 6
    call SetPlayerStartLocation( Player(6), 6 )
    call ForcePlayerStartLocation( Player(6), 6 )
    call SetPlayerColor( Player(6), ConvertPlayerColor(6) )
    call SetPlayerRacePreference( Player(6), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(6), false )
    call SetPlayerController( Player(6), MAP_CONTROL_USER )

    // Player 7
    call SetPlayerStartLocation( Player(7), 7 )
    call ForcePlayerStartLocation( Player(7), 7 )
    call SetPlayerColor( Player(7), ConvertPlayerColor(7) )
    call SetPlayerRacePreference( Player(7), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(7), false )
    call SetPlayerController( Player(7), MAP_CONTROL_USER )

    // Player 8
    call SetPlayerStartLocation( Player(8), 8 )
    call ForcePlayerStartLocation( Player(8), 8 )
    call SetPlayerColor( Player(8), ConvertPlayerColor(8) )
    call SetPlayerRacePreference( Player(8), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(8), false )
    call SetPlayerController( Player(8), MAP_CONTROL_USER )

    // Player 9
    call SetPlayerStartLocation( Player(9), 9 )
    call ForcePlayerStartLocation( Player(9), 9 )
    call SetPlayerColor( Player(9), ConvertPlayerColor(9) )
    call SetPlayerRacePreference( Player(9), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(9), false )
    call SetPlayerController( Player(9), MAP_CONTROL_USER )

    // Player 10
    call SetPlayerStartLocation( Player(10), 10 )
    call ForcePlayerStartLocation( Player(10), 10 )
    call SetPlayerColor( Player(10), ConvertPlayerColor(10) )
    call SetPlayerRacePreference( Player(10), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(10), false )
    call SetPlayerController( Player(10), MAP_CONTROL_USER )

    // Player 11
    call SetPlayerStartLocation( Player(11), 11 )
    call ForcePlayerStartLocation( Player(11), 11 )
    call SetPlayerColor( Player(11), ConvertPlayerColor(11) )
    call SetPlayerRacePreference( Player(11), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(11), false )
    call SetPlayerController( Player(11), MAP_CONTROL_USER )

    // Player 12
    call SetPlayerStartLocation( Player(12), 12 )
    call ForcePlayerStartLocation( Player(12), 12 )
    call SetPlayerColor( Player(12), ConvertPlayerColor(12) )
    call SetPlayerRacePreference( Player(12), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(12), false )
    call SetPlayerController( Player(12), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_020
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerState( Player(0), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerState( Player(1), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerState( Player(2), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(3), 0 )
    call SetPlayerState( Player(3), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(2), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )

    // Force: TRIGSTR_021
    call SetPlayerTeam( Player(4), 1 )
    call SetPlayerState( Player(4), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(5), 1 )
    call SetPlayerState( Player(5), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(6), 1 )
    call SetPlayerState( Player(6), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(7), 1 )
    call SetPlayerState( Player(7), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(6), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(6), true )

    // Force: TRIGSTR_022
    call SetPlayerTeam( Player(8), 2 )
    call SetPlayerState( Player(8), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(9), 2 )
    call SetPlayerState( Player(9), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(10), 2 )
    call SetPlayerState( Player(10), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(11), 2 )
    call SetPlayerState( Player(11), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(12), 2 )
    call SetPlayerState( Player(12), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(10), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(12), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(10), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(12), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(12), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(10), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(12), true )
    call SetPlayerAllianceStateAllyBJ( Player(12), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(12), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(12), Player(10), true )
    call SetPlayerAllianceStateAllyBJ( Player(12), Player(11), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(12), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(12), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(12), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(12), true )
    call SetPlayerAllianceStateVisionBJ( Player(12), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(12), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(12), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(12), Player(11), true )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 1 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 1 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 2, 2 )
    call SetStartLocPrio( 2, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 2, 1, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 3, 1 )
    call SetStartLocPrio( 3, 0, 2, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 1 )
    call SetStartLocPrio( 4, 0, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 5, 2 )
    call SetStartLocPrio( 5, 0, 6, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 1, 7, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 6, 1 )
    call SetStartLocPrio( 6, 0, 7, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 7, 1 )
    call SetStartLocPrio( 7, 0, 6, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 8, 3 )
    call SetStartLocPrio( 8, 0, 9, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 8, 1, 10, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 8, 2, 11, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 9, 3 )
    call SetStartLocPrio( 9, 0, 8, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 9, 1, 10, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 9, 2, 11, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 10, 3 )
    call SetStartLocPrio( 10, 0, 8, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 10, 1, 9, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 10, 2, 11, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 11, 3 )
    call SetStartLocPrio( 11, 0, 8, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 11, 1, 9, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 11, 2, 10, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 12, 12 )
    call SetStartLocPrio( 12, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 1, 1, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 2, 2, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 3, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 4, 4, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 5, 5, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 6, 6, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 7, 7, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 12, 8, 8, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 9, 9, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 12, 10, 10, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 12, 11, 11, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 12, 12 )
    call SetEnemyStartLocPrio( 12, 0, 0, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 1, 1, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 2, 2, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 3, 3, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 4, 4, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 5, 5, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 12, 6, 6, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 7, 7, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 8, 8, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 12, 9, 9, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 12, 10, 10, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 12, 11, 11, MAP_LOC_PRIO_HIGH )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -11008.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -9728.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 8704.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -11008.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 8704.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -9728.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "CityScapeDay" )
    call SetAmbientNightSound( "CityScapeNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_003" )
    call SetMapDescription( "TRIGSTR_005" )
    call SetPlayers( 13 )
    call SetTeams( 13 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, -5952.0, -3392.0 )
    call DefineStartLocation( 1, -5184.0, -3328.0 )
    call DefineStartLocation( 2, -5952.0, -4608.0 )
    call DefineStartLocation( 3, -5120.0, -4608.0 )
    call DefineStartLocation( 4, 2816.0, 2496.0 )
    call DefineStartLocation( 5, 3328.0, 2496.0 )
    call DefineStartLocation( 6, 2816.0, 3840.0 )
    call DefineStartLocation( 7, 3328.0, 3840.0 )
    call DefineStartLocation( 8, -832.0, -768.0 )
    call DefineStartLocation( 9, -832.0, -768.0 )
    call DefineStartLocation( 10, -832.0, -768.0 )
    call DefineStartLocation( 11, -832.0, -768.0 )
    call DefineStartLocation( 12, -832.0, -768.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

